
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxWrap from "../../Redux/ReduxWrap";
import ScrollToTop from "@/components/Scroll/TopScroll";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ensure RootLayout is exported as a standard client-side component
export default function RootLayout({ children }) {
  return (
    <ReduxWrap>
      <html lang="en">
        <body className={inter.className}>
        
          {children}
          <ScrollToTop></ScrollToTop>
         
        </body>
      </html>
    </ReduxWrap>
  );
}
